### ISSUE TITLE
Render transitions as AVI?

### ISSUE THREAD

**Issue by mschwarzer** [gre/glsl-transition#16]
Hi everyone,

is it possible to render a slideshow made with glsl-transitions as AVI or any other video format? I would like to render the slideshow server-side not with canvas.toDataUrl() in a browser.

Cheers
Malte

**Comment by gre** [comment]
Hi @mschwarzer ,

It is not currently possible because not implemented.

I agree this would be great and **technically this should work** (WebGL GLSL can be compiled to OpenGL GLSL via ANGLE).
I've started this discussion one year ago on this thread: https://github.com/glslio/transitions.glsl.io/issues/56

Which currently leads to a beginning of implementation of a plugin for "MLT" started by @rectalogic but it is unfinished.
- Best would be to natively implement some plugins to MLT/ffmpeg or any other tool but it takes a lot of time to make it.
- Another approach might be to try to "emulate WebGL" but this is quite uncertain and probably slower.

This is open to contribution.

Thanks
